In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [2]:
train = "train-00000-of-00001-d5675d98fde8c367"

input_file = f"raw/ContractNLI_reuben/{train}.parquet"
df = pd.read_parquet(input_file)
df = df[df['label'] != 'notmentioned']

# df.to_json(json_file, orient='records', lines=True)

In [39]:
df.dtypes

document_id        int64
file_name            str
text                 str
hypothesis_id        str
hypothesis           str
label                str
evidence_spans    object
evidence_texts    object
dtype: object

In [25]:
df.label.value_counts()

label
entailment       3530
contradiction     841
Name: count, dtype: int64

In [33]:
df.shape

(4371, 8)

In [3]:
full_document = df.groupby(['document_id']).nth(0)[['document_id', 'text']]
full_document.head(1)

   document_id  \
1           34

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 text
1  NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT\nThis NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT (“Agreement”) is made by and between:\n(i) the Office of the United Nations High Commissioner for Refugees, having its headquarters located at 94 rue de Montbrillant, 1202 Geneva, Switzerland (hereinafter “UNHCR” or the “Discloser”); and\n(ii) ________________________ , a company established in accordance with the laws of ________________________ and having its principal offices located at ________________________________________________ (hereinafter the “Bidder” or the “Recipient”).\nThe Discloser and Recipient are also referred to collectively as the “Parties” and individually as a “Party”.\nRECITALS\nWHEREAS in connection with RFP/2014/620, Request for Proposal for the provision Off-the-shelf Soft-skill, IT Online and HR specific E-learning Courses (the “RFP”), it is advantageous to share certain data and information with the Bidder participating in the RFP;\nWHEREAS UNHCR agrees to provide such data and information to the Bidder for the sole purpose of preparing its Proposal under said RFP;\nWHEREAS the Bidder is willing to ensure that UNHCR’s data and information will be held in strict confidence and only used for the permitted purpose;\nNOW, THEREFORE, the Parties agree as follows:\n1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.\n2. The Confidential Information that is delivered or otherwise disclosed by the Discloser to the Recipient shall be held in trust and confidence by the Recipient and shall be handled as follows:\n2.1 The Recipient shall use the same care and discretion to avoid disclosure, publication or dissemination of the Confidential Information as it uses with its own similar information that it does not wish to disclose, publish or disseminate;\n2.2 The Recipient shall use the Confidential Information solely for the purpose for which it was disclosed;\n2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to:\n2.3.1 Any other party with the Discloser’s prior written consent; and\n2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:\n2.3.2.1 a corporate entity in which the Party owns or otherwise controls, whether directly or indirectly, over fifty percent (50%) of voting shares thereof; or,\n2.3.2.2 any entity over which the Party exercises effective managerial control; or,\n2.3.2.3 for UNHCR, a principal or subsidiary organ of the United Nations established in accordance with the Charter of the United Nations.\n2.4 The Recipient may disclose the Confidential Information to the extent required by law, provided that, subject to and without any waiver of the privileges and immunities of UNHCR, the Recipient will give UNHCR sufficient prior notice of a request for the disclosure of the Confidential Information in order to allow UNHCR to have a reasonable opportunity to take protective measures or such other action as may be appropriate before any such disclosure is made.\n2.5 The Recipient shall not be precluded from disclosing the Confidential Information that is (i) obtained by the Recipient without restriction from a third party who is not in breach of any obligation as to confidentiality to the owner of such Confidential Information or any other person, or (ii) disclosed by the Discloser to a third party without any obligation of confidentiality, or (iii) previously known by the Recipient, or (iv) at any time is developed by the Recipient completely independently of any disclosures hereunder.\n2.6 The Recipient will not copy or reproduce the Confidential Information except as reasonably required for the purposes contemplated in this Agreement, and will ensure that any confidentiality or other proprietary rights notices on the Confidential Information are reproduced on all copies.\n3. The Recipient acknowledges that UNHCR hereto makes no any representation or warranty, express or implied, as to the accuracy or completeness of the Confidential Information.\n4. Nothing in this Agreement is to be construed as granting the Recipient, by implication or otherwise, any right whatsoever with respect to the Confidential Information or part thereof.\n5. All Confidential Information in any form and any medium, including all copies thereof, disclosed to the Recipient shall be returned to UNHCR or destroyed: (a) if a business relationship is not entered into with UNHCR on or before the date which is three (3) months after the date both Parties have signed the Agreement; or (b) promptly upon request by the UNHCR at any time.\n6. The Recipient agrees to indemnify UNHCR in respect of any expenses, losses, damages, costs, claims or liability UNHCR may suffer or incur as a result of an act or omission by the Recipient or its employees, consultants and agents in connection with the Confidential Information and the Recipient’s obligations under this Agreement.\n7. Nothing in this Agreement shall be construed as obligating any Party to continue any discussions or to enter into a business relationship.\n8. This Agreement shall enter into force on the date it is signed by both Parties. Either Party may terminate the working relationship contemplated by this Agreement by providing written notice to the other, provided, however, that the obligations and restrictions hereunder regarding the Confidential Information shall remain effective following any such termination or any other termination or expiration of this Agreement.\n9. Any dispute, controversy or claim between the Parties arising out of, this Agreement or the breach, termination or invalidity thereof, unless settled amicably within twenty (20) days after receipt by one Party of the other Party's request for such amicable settlement, shall be referred by either Party to arbitration in accordance with the UNCITRAL Arbitration Rules then obtaining, including provisions on applicable law. The arbitral tribunal shall have no authority to award punitive damages. In addition, unless otherwise expressly provided in this Agreement, the arbitral tribunal shall have no authority to award interest. The Parties shall be bound by any arbitration award rendered as a result of such arbitration as the final adjudication of any such controversy, claim or dispute.\n10. Nothing in or relating to this Agreement shall be deemed a waiver, express or implied, of any of the privileges and immunities of the United Nations, including UNHCR as its subsidiary organ.\n11. The Recipient shall not advertise or otherwise make public the fact that it has a confidential relationship with UNHCR, nor shall the Recipient, in any manner whatsoever use the name, emblem, or official seal of the United Nations or UNHCR, or any abbreviation of the name of the United Nations or UNHCR in connection with its business or otherwise.\n12. If any provision of this Agreement shall be held to be invalid, illegal or unenforceable, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired.\n13. This Agreement constitutes the entire agreement concerning the subject matter hereof above and supersedes all prior representations, agreements and understandings, whether written or oral, by and between the Parties on the subject hereof.\n14. The Parties acknowledge and agree that their representatives who have signed this Agreement had full authority to do so and to fully bind the Party being represented by doing so.\nIN WITNESS WHEREOF, the Parties, acting through their authorized representatives, have caused this Agreement to be signed on the dates set forth below:\nFor and on behalf of UNHCR: For and on behalf of the Bidder:\n________________________ ________________________\n Name: Name:\nTitle: Title:\n Date: Date:\n

In [4]:
evidence_list = df.head(1)['evidence_texts'].values[0].tolist()
# Turn evidence into a single string separated by newlines
evidence_list_str = "\n".join(evidence_list)
hypothesis = df.head(1)['hypothesis'].values[0]
hypo_label = df.head(1)['label'].values[0]
{'hypothesis': hypothesis,
'evidence': evidence_list_str,
'hypothesis_label': hypo_label,}

{'hypothesis': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.',
 'evidence': '5. All Confidential Information in any form and any medium, including all copies thereof, disclosed to the Recipient shall be returned to UNHCR or destroyed: \n(a) if a business relationship is not entered into with UNHCR on or before the date which is three (3) months after the date both Parties have signed the Agreement; or ',
 'hypothesis_label': 'entailment'}

In [ ]:
def hypo_inferred(row):
    # Turn evidence into a single string separated by newlines
    evidence_list = row['evidence_texts'].tolist()
    evidence_list_str = "\n".join(evidence_list)

    hypothesis = row['hypothesis']
    hypo_label = row['label']

    data_dict = {'hypothesis': hypothesis,
            'evidence': evidence_list_str,
            'hypothesis_label': hypo_label}
    
    return str(data_dict)

hypotheses_inferred = df.copy()[['document_id','evidence_texts','hypothesis','label']]
hypotheses_inferred['inference'] = hypotheses_inferred.apply(hypo_inferred, axis=1)
hypotheses_inferred = hypotheses_inferred[['document_id', 'inference']]

In [17]:
hypotheses_inferred_byid = hypotheses_inferred.groupby('document_id')['inference'].agg(list).reset_index()
hypotheses_inferred_byid.head(1)

   document_id  \
0           34

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      inference
0  [{'hypothesis': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.', 'evidence': '5. All Confidential Information in any form and any medium, including all copies thereof, disclosed to the Recipient shall be returned to UNHCR or destroyed: \n(a) if a business relationship is not entered into with UNHCR on or before the date which is three (3) months after the date both Parties have signed the Agreement; or ', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Agreement shall not grant Receiving Party any right to Confidential Information.', 'evidence': '4. Nothing in this Agreement is to be construed as granting the Recipient, by implication or otherwise, any right whatsoever with respect to the Confidential Information or part thereof.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.', 'evidence': '11. The Recipient shall not advertise or otherwise make public the fact that it has a confidential relationship with UNHCR, nor shall the Recipient, in any manner whatsoever use the name, emblem, or official seal of the United Nations or UNHCR, or any abbreviation of the name of the United Nations or UNHCR in connection with its business or otherwise.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'All Confidential Information shall be expressly identified by the Disclosing Party.', 'evidence': '1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Some obligations of Agreement may survive termination of Agreement.', 'evidence': 'Either Party may terminate the working relationship contemplated by this Agreement by providing written notice to the other, provided, however, that the obligations and restrictions hereunder regarding the Confidential Information shall remain effective following any such termination or any other termination or expiration of this Agreement.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party may independently develop information similar to Confidential Information.', 'evidence': 'The Recipient shall not be precluded from disclosing the Confidential Information that is \n(iv) at any time is developed by the Recipient completely independently of any disclosures hereunder.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Confidential Information may include verbally conveyed information.', 'evidence': '1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).', 'evidence': '2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to:\n2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party may create a copy of some Confidential Information in some circumstances.', 'evidence': 'The Recipient will not copy or reproduce the Confidential Information except as reasonably required for the purposes contemplated in this Agreement, and will ensure that any confidentiality or other proprietary rights notices on the Confidential Information are reproduced on all copies.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.', 'evidence': 'The Recipient may disclose the Confidential Information to the extent required by law, provided that, subject to and without any waiver of the privileges and immunities of UNHCR, the Recipient will give UNHCR sufficient prior notice of a request for the disclosure of the Confidential Information in order to allow UNHCR to have a reasonable opportunity to take protective measures or such other action as may be appropriate before any such disclosure is made.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party may acquire information similar to Confidential Information from a third party.', 'evidence': 'The Recipient shall not be precluded from disclosing the Confidential Information that is \n(i) obtained by the Recipient without restriction from a third party who is not in breach of any obligation as to confidentiality to the owner of such Confidential Information or any other person, or ', 'hypothesis_label': 'entailment'}, {'hypothesis': "Receiving Party may share some Confidential Information with some of Receiving Party's employees.", 'evidence': '2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to:\n2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:\n2.3.2.2 any entity over which the Party exercises effective managerial control; or,', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.', 'evidence': 'The Recipient shall use the Confidential Information solely for the purpose for which it was disclosed;', 'hypothesis_label': 'entailment'}]

In [18]:
final = pd.merge(full_document, hypotheses_inferred_byid, on='document_id', how='inner')
final.shape

(423, 3)

In [24]:
filename = "train"

output_file = f"processed/{filename}.jsonl"

final.to_json(output_file, orient='records', lines=True)

In [27]:
def process_dataset(input_file, output_file):
    df = pd.read_parquet(input_file)
    df = df[df['label'] != 'notmentioned']

    # full document
    full_document = df.groupby(['document_id']).nth(0)[['document_id', 'text']]

    # hypotheses

    def hypo_inferred(row):
        """
        Helper function
        """
        # Turn evidence into a single string separated by newlines
        evidence_list = row['evidence_texts'].tolist()
        evidence_list_str = "\n".join(evidence_list)

        hypothesis = row['hypothesis']
        hypo_label = row['label']

        data_dict = {'hypothesis': hypothesis,
                'evidence': evidence_list_str,
                'hypothesis_label': hypo_label}
        # return the dictionary as a string
        return str(data_dict)

    hypotheses_inferred = df.copy()[['document_id','evidence_texts','hypothesis','label']]
    hypotheses_inferred['inference'] = hypotheses_inferred.apply(hypo_inferred, axis=1)
    hypotheses_inferred = hypotheses_inferred[['document_id', 'inference']]

    # aggregate the hypo_infer strings into a list by document_id
    hypotheses_inferred_byid = hypotheses_inferred.groupby('document_id')['inference'].agg(list).reset_index()

    # merge full document, and processed hypotheses columns
    # columns are now: document_id, text, inference (str of long dictionary)
    final_df = pd.merge(full_document, hypotheses_inferred_byid, on='document_id', how='inner')

    # write to new location
    final_df.to_json(output_file, orient="records", lines=True)
    print(f"{input_file} processed and written to {output_file}")

In [28]:
input_filename = "train-00000-of-00001-d5675d98fde8c367"
input_file = f"raw/ContractNLI_reuben/{input_filename}.parquet"

output_filename = "train"
output_file = f"processed/{output_filename}.jsonl"

process_dataset(input_file, output_file)

raw/ContractNLI_reuben/train-00000-of-00001-d5675d98fde8c367.parquet processed and written to processed/train.jsonl

In [29]:
input_filename = "test-00000-of-00001-762092f06e2d7b48"
input_file = f"raw/ContractNLI_reuben/{input_filename}.parquet"

output_filename = "test"
output_file = f"processed/{output_filename}.jsonl"

process_dataset(input_file, output_file)

raw/ContractNLI_reuben/test-00000-of-00001-762092f06e2d7b48.parquet processed and written to processed/test.jsonl

In [30]:
input_filename = "validation-00000-of-00001-3714eab8cedda2e5"
input_file = f"raw/ContractNLI_reuben/{input_filename}.parquet"

output_filename = "validation"
output_file = f"processed/{output_filename}.jsonl"

process_dataset(input_file, output_file)

raw/ContractNLI_reuben/validation-00000-of-00001-3714eab8cedda2e5.parquet processed and written to processed/validation.jsonl