In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [2]:
train = "train-00000-of-00001-d5675d98fde8c367"

input_file = f"raw/ContractNLI_reuben/{train}.parquet"
df = pd.read_parquet(input_file)
df = df[df['label'] != 'notmentioned']

# df.to_json(json_file, orient='records', lines=True)

In [39]:
df.dtypes

document_id        int64
file_name            str
text                 str
hypothesis_id        str
hypothesis           str
label                str
evidence_spans    object
evidence_texts    object
dtype: object

In [25]:
df.label.value_counts()

label
entailment       3530
contradiction     841
Name: count, dtype: int64

In [33]:
df.shape

(4371, 8)

# Ignore

In [39]:
full_document = df.groupby(['document_id']).nth(0)[['document_id', 'text']]
full_document[full_document['document_id']==91]

    document_id  \
85           91

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               text

In [28]:
df.document_id.unique()

array([ 34,  86,  87,  88,  89,  91,  92,  93,  94,  95,  96,  98, 100,
       101, 102, 103, 104, 105, 106, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 118, 119, 120, 121, 122, 123, 124, 125, 126, 128, 130,
       131, 132, 133, 134, 135, 136, 137, 139, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 150, 151, 153, 154, 155, 156, 158, 159, 160,
       161, 162, 163, 164, 166, 167, 168, 169, 170, 171, 172, 173, 174,
       176, 177, 178, 179, 180, 182, 183, 184, 186, 187, 188, 189, 191,
       192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
       206, 207, 208, 209, 210, 211, 214, 215, 216, 217, 219, 220, 221,
       222, 223, 224, 226, 229, 230, 231, 232, 233, 234, 235, 236, 237,
       238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250,
       251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263,
       264, 265, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 290, 291,
       292, 294, 295, 297, 298, 299, 300, 302, 303, 304, 305, 306, 308,
       309, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 322, 323,
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 355, 356, 358, 359, 360, 362, 363, 364, 365, 366,
       367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379,
       380, 382, 383, 384, 385, 386, 388, 390, 391, 393, 394, 396, 397,
       399, 402, 403, 404, 407, 409, 410, 414, 415, 416, 417, 418, 419,
       420, 421, 422, 423, 424, 425, 426, 427, 428, 430, 431, 434, 436,
       437, 438, 439, 441, 442, 443, 445, 447, 448, 449, 450, 453, 454,
       457, 458, 459, 460, 461, 462, 463, 464, 466, 467, 468, 469, 470,
       472, 473, 474, 475, 477, 481, 483, 484, 485, 487, 489, 490, 492,
       494, 495, 499, 500, 501, 502, 503, 504, 505, 509, 512, 513, 515,
       516, 517, 518, 519, 520, 522, 524, 525, 527, 529, 530, 531, 534,
       535, 536, 538, 541, 545, 548, 550, 551, 553, 554, 556, 557, 559,
       560, 561, 562, 566, 567, 568, 569, 570, 571, 572, 573, 574, 576,
       577, 578, 579, 580, 581, 583, 587, 588, 589, 592, 593, 594, 597,
       599, 602, 603, 604, 607, 608, 609, 612, 613, 614, 615, 616, 617,
       618, 619, 620, 621, 622, 623, 624], dtype=int64)

In [40]:
df[df['document_id']==91][['hypothesis', 'label', 'evidence_texts', 'hypothesis_id']]

,hypothesis,label,evidence_texts,hypothesis_id
85,Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information.,entailment,"[IV. NO REVERSE ENGINEERING; WORK PRODUCT: Receiving Party shall not reverse-engineer, analyze, attempt to duplicate or otherwise attempt to determine the design or method of compiling samples, prototypes or products of the Originating Party except pursuant to a mutually acceptable, written agreement executed by the parties. ]",nda-11
87,Agreement shall not grant Receiving Party any right to Confidential Information.,entailment,[No express or implied license under any intellectual property rights of either party is granted or conveyed to the other party under this Agreement. ],nda-15
89,Confidential Information shall only include technical information.,contradiction,"[A. “Confidential Information” as used herein any and all confidential and/or proprietary information concerning the Originating Party’s business and such party’s trade secrets, proprietary data and business data, whether oral or written, tangible or intangible, which is disclosed to or learned by the Receiving Party in the course of the Discussions or otherwise while working with the Originating Party, and/or discovered, developed, conceived, originated, appreciably modified, or prepared in scope of Receiving Party’s relationship with the Originating Party, including but not limited to the following:, 1. Business plans, acquisition plans, expansion plans, business development plans;, 2. Financial information, personnel information, training information, management systems and recruitment strategies;, 3. All commercial data relating to the business and products of Originating Party;, 4. Identity and contact information regarding vendors and suppliers;, 6. Pricing and marketing/business strategies;, 8. Customer identities and customer contact information;, 9. Customer credit information;, 10. Information regarding customer preferences and particularized needs;, 11. Product development strategies, expansion plans, and internal business plans, procedures, or methods of operation; and]",nda-2
91,Some obligations of Agreement may survive termination of Agreement.,entailment,[Both parties further agree that their obligations under this paragraph survive the termination of the relationship between the two parties.],nda-19
92,Receiving Party may independently develop information similar to Confidential Information.,entailment,"[13. “Confidential Information” shall not include information which, now or in the future, is available to the public (other than through improper disclosure by the Receiving Party); information rightly acquired from a third party without any obligation of confidentiality; information that is independently developed without the use of any Confidential Information; or information already known by Receiving Party prior to disclosure by Originating Party, as demonstrated by written evidence.]",nda-12
94,Confidential Information may include verbally conveyed information.,entailment,"[A. “Confidential Information” as used herein any and all confidential and/or proprietary information concerning the Originating Party’s business and such party’s trade secrets, proprietary data and business data, whether oral or written, tangible or intangible, which is disclosed to or learned by the Receiving Party in the course of the Discussions or otherwise while working with the Originating Party, and/or discovered, developed, conceived, originated, appreciably modified, or prepared in scope of Receiving Party’s relationship with the Originating Party, including but not limited to the following:]",nda-3
95,Receiving Party shall not solicit some of Disclosing Party's representatives.,entailment,"[V. NON-SOLICITATION OF EMPLOYEES AND/OR CONTRACTORS: Receiving Party recognizes and acknowledges that, while engaged in Discussions and/or while involved in a Business Relationship, such party will be in a position to utilize Originating Party’s goodwill and have access to and/or utilize Confidential Information of Originating Party that would enable Receiving Party to take advantage of that goodwill and/or Confidential Information to the detriment of the Originating Party, by attempting, for example, to recruit or solicit employees, and/or contractors of Originating Party. , Therefore, in consideration of the mutual agreements made in this Agreement, during the course of the Business Relationship and for a period of 36 months after termination of the Business Relationship, Receiving Party agrees not to directly or indirectly communicate, solicit, induce, hire, recruit, take away, employ, endeavor to employ (on Receiving Party’s own behalf or on behalf of any other person or entity) or attempt to influence any employee or contractor in any way that may have the effect of causing the cessation or curtailment of their respective relationships with Originating Party.]",nda-18
97,Receiving Party may create a copy of some Confidential Information in some circumstances.,contradiction,"[Receiving Party therefore agrees that neither it nor its , Representatives will at any time make any independent business or personal use of, retain, copy, divulge, disclose, reveal or communicate to any other person or organization (except as expressly authorized in writing by Originating Party, as required to analyze the Business Relationship or as required to fulfill Receiving Party’s obligations to Originating Party) any Confidential Information. , IV. NO REVERSE ENGINEERING; WORK PRODUCT: Receiving Party shall not reverse-engineer, analyze, attempt to duplicate or otherwise attempt to determine the design or method of compiling samples, prototypes or products of the Originating Party except pursuant to a mutually acceptable, written agreement executed by the parties. ]",nda-17
98,"Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.",entailment,"[III. LEGALLY REQUIRED DISCLOSURES: If Receiving Party is requested to disclose any Confidential Information of the Originating Party under applicable law, in any judicial or administrative proceeding, or in response to a formal request of a regulatory or governmental authority (including law enforcement), then, except as otherwise required to comply with applicable law, the Receiving Party shall promptly notify the Originating Party of such request so that Originating Party may resist such disclosure or seek an appropriate protective order, and shall provide all information and assistance reasonably requested by Originating Party in connection therewith, at the Originating Party’s sole expense. ]",nda-8
99,Receiving Party may acquire information similar to Confidential Information from a third party.,entailment,"[13. “Confidential Information” shall not include information which, now or in the future, is available to the public (other than through improper disclosure by the Receiving Party); information rightly acquired from a third party without any obligation of confidentiality; information that is independently developed without the use of any Confidential Information; or information already known by Receiving Party prior to disclosure by Originating Party, as demonstrated by written evidence.]",nda-13
101,Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.,entailment,"[Receiving Party therefore agrees that neither it nor its , Representatives will at any time make any independent business or personal use of, retain, copy, divulge, disclose, reveal or communicate to any other person or organization (except as expressly authorized in writing by Originating Party, as required to analyze the Business Relationship or as required to fulfill Receiving Party’s obligations to Originating Party) any Confidential Information. ]",nda-4

# Start here

In [ ]:
evidence_list = df.head(1)['evidence_texts'].values[0].tolist()
# Turn evidence into a single string separated by newlines
evidence_list_str = "\n".join(evidence_list)
hypothesis = df.head(1)['hypothesis'].values[0]
hypo_label = df.head(1)['label'].values[0]

{'hypothesis': hypothesis,
'evidence': evidence_list_str,
'hypothesis_label': hypo_label,}

{'hypothesis': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.',
 'evidence': '5. All Confidential Information in any form and any medium, including all copies thereof, disclosed to the Recipient shall be returned to UNHCR or destroyed: \n(a) if a business relationship is not entered into with UNHCR on or before the date which is three (3) months after the date both Parties have signed the Agreement; or ',
 'hypothesis_label': 'entailment'}

In [ ]:
def hypo_inferred(row):
    # Turn evidence into a single string separated by newlines
    evidence_list = row['evidence_texts'].tolist()
    evidence_list_str = "\n".join(evidence_list)

    hypothesis = row['hypothesis']
    hypo_label = row['label']

    data_dict = {'hypothesis': hypothesis,
            'evidence': evidence_list_str,
            'hypothesis_label': hypo_label}
    
    return str(data_dict)

hypotheses_inferred = df.copy()[['document_id','evidence_texts','hypothesis','label']]
hypotheses_inferred['inference'] = hypotheses_inferred.apply(hypo_inferred, axis=1)
hypotheses_inferred = hypotheses_inferred[['document_id', 'inference']]

In [17]:
hypotheses_inferred_byid = hypotheses_inferred.groupby('document_id')['inference'].agg(list).reset_index()
hypotheses_inferred_byid.head(1)

   document_id  \
0           34

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      inference
0  [{'hypothesis': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.', 'evidence': '5. All Confidential Information in any form and any medium, including all copies thereof, disclosed to the Recipient shall be returned to UNHCR or destroyed: \n(a) if a business relationship is not entered into with UNHCR on or before the date which is three (3) months after the date both Parties have signed the Agreement; or ', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Agreement shall not grant Receiving Party any right to Confidential Information.', 'evidence': '4. Nothing in this Agreement is to be construed as granting the Recipient, by implication or otherwise, any right whatsoever with respect to the Confidential Information or part thereof.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.', 'evidence': '11. The Recipient shall not advertise or otherwise make public the fact that it has a confidential relationship with UNHCR, nor shall the Recipient, in any manner whatsoever use the name, emblem, or official seal of the United Nations or UNHCR, or any abbreviation of the name of the United Nations or UNHCR in connection with its business or otherwise.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'All Confidential Information shall be expressly identified by the Disclosing Party.', 'evidence': '1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Some obligations of Agreement may survive termination of Agreement.', 'evidence': 'Either Party may terminate the working relationship contemplated by this Agreement by providing written notice to the other, provided, however, that the obligations and restrictions hereunder regarding the Confidential Information shall remain effective following any such termination or any other termination or expiration of this Agreement.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party may independently develop information similar to Confidential Information.', 'evidence': 'The Recipient shall not be precluded from disclosing the Confidential Information that is \n(iv) at any time is developed by the Recipient completely independently of any disclosures hereunder.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Confidential Information may include verbally conveyed information.', 'evidence': '1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).', 'evidence': '2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to:\n2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party may create a copy of some Confidential Information in some circumstances.', 'evidence': 'The Recipient will not copy or reproduce the Confidential Information except as reasonably required for the purposes contemplated in this Agreement, and will ensure that any confidentiality or other proprietary rights notices on the Confidential Information are reproduced on all copies.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.', 'evidence': 'The Recipient may disclose the Confidential Information to the extent required by law, provided that, subject to and without any waiver of the privileges and immunities of UNHCR, the Recipient will give UNHCR sufficient prior notice of a request for the disclosure of the Confidential Information in order to allow UNHCR to have a reasonable opportunity to take protective measures or such other action as may be appropriate before any such disclosure is made.', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party may acquire information similar to Confidential Information from a third party.', 'evidence': 'The Recipient shall not be precluded from disclosing the Confidential Information that is \n(i) obtained by the Recipient without restriction from a third party who is not in breach of any obligation as to confidentiality to the owner of such Confidential Information or any other person, or ', 'hypothesis_label': 'entailment'}, {'hypothesis': "Receiving Party may share some Confidential Information with some of Receiving Party's employees.", 'evidence': '2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to:\n2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:\n2.3.2.2 any entity over which the Party exercises effective managerial control; or,', 'hypothesis_label': 'entailment'}, {'hypothesis': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.', 'evidence': 'The Recipient shall use the Confidential Information solely for the purpose for which it was disclosed;', 'hypothesis_label': 'entailment'}]

In [18]:
final = pd.merge(full_document, hypotheses_inferred_byid, on='document_id', how='inner')
final.shape

(423, 3)

In [24]:
filename = "train"

output_file = f"processed/{filename}.jsonl"

final.to_json(output_file, orient='records', lines=True)

In [27]:
def process_dataset(input_file, output_file):
    df = pd.read_parquet(input_file)
    df = df[df['label'] != 'notmentioned']

    # full document
    full_document = df.groupby(['document_id']).nth(0)[['document_id', 'text']]

    # hypotheses

    def hypo_inferred(row):
        """
        Helper function
        """
        # Turn evidence into a single string separated by newlines
        evidence_list = row['evidence_texts'].tolist()
        evidence_list_str = "\n".join(evidence_list)

        hypothesis = row['hypothesis']
        hypo_label = row['label']

        data_dict = {'hypothesis': hypothesis,
                'evidence': evidence_list_str,
                'hypothesis_label': hypo_label}
        # return the dictionary as a string
        return str(data_dict)

    hypotheses_inferred = df.copy()[['document_id','evidence_texts','hypothesis','label']]
    hypotheses_inferred['inference'] = hypotheses_inferred.apply(hypo_inferred, axis=1)
    hypotheses_inferred = hypotheses_inferred[['document_id', 'inference']]

    # aggregate the hypo_infer strings into a list by document_id
    hypotheses_inferred_byid = hypotheses_inferred.groupby('document_id')['inference'].agg(list).reset_index()

    # merge full document, and processed hypotheses columns
    # columns are now: document_id, text, inference (str of long dictionary)
    final_df = pd.merge(full_document, hypotheses_inferred_byid, on='document_id', how='inner')

    # write to new location
    final_df.to_json(output_file, orient="records", lines=True)
    print(f"{input_file} processed and written to {output_file}")

In [28]:
input_filename = "train-00000-of-00001-d5675d98fde8c367"
input_file = f"raw/ContractNLI_reuben/{input_filename}.parquet"

output_filename = "train"
output_file = f"processed/{output_filename}.jsonl"

process_dataset(input_file, output_file)

raw/ContractNLI_reuben/train-00000-of-00001-d5675d98fde8c367.parquet processed and written to processed/train.jsonl

In [29]:
input_filename = "test-00000-of-00001-762092f06e2d7b48"
input_file = f"raw/ContractNLI_reuben/{input_filename}.parquet"

output_filename = "test"
output_file = f"processed/{output_filename}.jsonl"

process_dataset(input_file, output_file)

raw/ContractNLI_reuben/test-00000-of-00001-762092f06e2d7b48.parquet processed and written to processed/test.jsonl

In [30]:
input_filename = "validation-00000-of-00001-3714eab8cedda2e5"
input_file = f"raw/ContractNLI_reuben/{input_filename}.parquet"

output_filename = "validation"
output_file = f"processed/{output_filename}.jsonl"

process_dataset(input_file, output_file)

raw/ContractNLI_reuben/validation-00000-of-00001-3714eab8cedda2e5.parquet processed and written to processed/validation.jsonl