In [1]:
import mlrun

from dotenv import load_dotenv
# Loads AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and MLRUN_AWS_ROLE_ARN
load_dotenv() 

import os
# https://docs.mlrun.org/en/stable/store/datastore.html#s3
# print(os.environ['AWS_ACCESS_KEY_ID'])
# print(os.environ['AWS_SECRET_ACCESS_KEY'])
# print(os.environ['MLRUN_AWS_ROLE_ARN'])

from pathlib import Path

artifact_path = Path.cwd().parent #/ "mlrun-data/"
artifact_path = str(artifact_path.as_posix()) # convert windows path to unix path
artifact_path = "file://" + artifact_path
print(artifact_path)
p = mlrun.set_environment(api_path="http://localhost:8080", artifact_path=artifact_path)

project = mlrun.load_project(name='finetune-legal-extractor', context="../") # project yaml must be in this directory

# Verify it loaded correctly by checking its status or printing the config
# print(project.to_yaml())

c:\Work\Folder_1\Project_folder\LLM_project_3_FineTune_MLOps\Finetune-legal-llm-mlops\.venv\lib\site-packages\google\auth\__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
c:\Work\Folder_1\Project_folder\LLM_project_3_FineTune_MLOps\Finetune-legal-llm-mlops\.venv\lib\site-packages\google\oauth2\__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

file://c:/Work/Folder_1/Project_folder/LLM_project_3_FineTune_MLOps/Finetune-legal-llm-mlops

In [2]:
from datetime import datetime

run_obj = project.run(
    name="register_raw_datasets",
    arguments={
        "source_path": "s3://legal-llama-data/raw",
        "version": datetime.now().strftime("%Y%m%d_%H%M")
    },
    local=True,   # Run the pipeline sequence locally
    watch=True    # Print the progress to the console
)

> 2026-04-12 20:36:31,526 [warning] WARNING!, You seem to have uncommitted git changes, use .push()

> 2026-04-12 20:36:31,676 [info] Storing function: {"db":null,"name":"raw-proc-process-raw","uid":"f8b01fadf2ae4083b0c11b043aea0de2"}
s3://legal-llama-data/raw/train.parquet processed and written to s3://legal-llama-data/processed_training/20260412_2036

> 2026-04-12 20:36:51,267 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}
> 2026-04-12 20:36:51,267 [info] Storing function: {"db":null,"name":"raw-proc-process-raw","uid":"f80deead6d154be8b6f3c8d582572921"}
s3://legal-llama-data/raw/validation.parquet processed and written to s3://legal-llama-data/processed_training/20260412_2036

> 2026-04-12 20:36:58,212 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}
> 2026-04-12 20:36:58,214 [info] Storing function: {"db":null,"name":"raw-proc-process-raw","uid":"70d4292d65094f249555b73d16b5eb8a"}
s3://legal-llama-data/raw/test.parquet processed and written to s3://legal-llama-data/processed_training/20260412_2036

> 2026-04-12 20:37:07,216 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}

> 2026-04-12 20:37:07,374 [info] Started run workflow finetune-legal-extractor-register_raw_datasets with run id = '996180db96be47b4871a207974a662f5' by local engine

In [7]:
from IPython.display import display

# Testing direct access to S3 data
data_uri = "s3://legal-llama-data/raw/test.parquet"
# Fetch the item and immediately convert it to a Pandas DataFrame
df = mlrun.get_dataitem(data_uri).as_df() #this reads into a dataframe and only works if the file is a csv/parquet... jsonl does not work
display(df.head())

data_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_test_data:latest"
data_pointer = mlrun.get_dataitem(data_uri)
print(data_pointer.url) # S3 path

,document_id,file_name,text,hypothesis_id,hypothesis,label,evidence_spans,evidence_texts
0,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-11,Receiving Party shall not reverse engineer any...,notmentioned,[],[]
1,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-16,Receiving Party shall destroy or return some C...,entailment,"[[12366, 12998], [12999, 13094], [13095, 13136]]",[The Recipient shall immediately return and re...
2,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-15,Agreement shall not grant Receiving Party any ...,entailment,"[[6094, 6220]]","[No other right or license, whether expressed ..."
3,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-10,Receiving Party shall not disclose the fact th...,notmentioned,[],[]
4,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-2,Confidential Information shall only include te...,contradiction,"[[3254, 3518], [4167, 4394]]","[For purposes of this Agreement, ""Confidential..."

s3://legal-llama-data/processed_training/20260412_2036/raw-proc-process-raw/0/test_data.parquet

In [8]:
# Testing data versioning and access to registered datasets in MLRun
data_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_train_data:latest"
data_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_test_data:20260412_2036"

# Fetch the item and immediately convert it to a Pandas DataFrame
df = mlrun.get_dataitem(data_uri).as_df()
print(df.head(1)['inference'][0])

[{'hypothesis': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information.", 'hypothesis_id': 'nda-11', 'hypothesis_label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.', 'hypothesis_id': 'nda-16', 'hypothesis_label': 'entailment', 'source_clause': 'The Recipient shall immediately return and redeliver to the other all tangible material embodying the JEA Confidential Information provided hereunder and all notes, summaries, memoranda, drawings, manuals, records, excerpts or derivative information deriving there from and all other documents or materials ("Notes") (and all copies of any of the foregoing, including "copies" that have been converted to computerized media in the form of image, data or word processing files either manually or by image capture) based on or including any JEA Confidential Information, in whatever form of storage or retrieval, upon the earlier of -. I. the completion or termination of the dealings between the parties contemplated hereunder; or. II. the termination of this Agreement; or'}
 {'hypothesis': 'Agreement shall not grant Receiving Party any right to Confidential Information.', 'hypothesis_id': 'nda-15', 'hypothesis_label': 'entailment', 'source_clause': 'No other right or license, whether expressed or implied, in the Confidential Information is granted to the Parties hereunder. '}
 {'hypothesis': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.', 'hypothesis_id': 'nda-10', 'hypothesis_label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'Confidential Information shall only include technical information.', 'hypothesis_id': 'nda-2', 'hypothesis_label': 'contradiction', 'source_clause': 'For purposes of this Agreement, "Confidential Information" means any data or information that is proprietary to the Parties and not generally known to the public, whether in tangible or intangible form, whenever and however disclosed, including but not limited to:. g. any Copyright application code, source code, technical design (not released for open use), trade secret, scientific or technical information, invention, design, process, procedure, formula, improvement, technology or method;'}
 {'hypothesis': 'All Confidential Information shall be expressly identified by the Disclosing Party.', 'hypothesis_id': 'nda-1', 'hypothesis_label': 'contradiction', 'source_clause': 'For purposes of this Agreement, "Confidential Information" means any data or information that is proprietary to the Parties and not generally known to the public, whether in tangible or intangible form, whenever and however disclosed, including but not limited to:'}
 {'hypothesis': 'Some obligations of Agreement may survive termination of Agreement.', 'hypothesis_id': 'nda-19', 'hypothesis_label': 'entailment', 'source_clause': "b. Notwithstanding the foregoing, the parties' duty to hold in confidence Confidential Information that was disclosed during term shall remain in effect indefinitely."}
 {'hypothesis': 'Receiving Party may independently develop information similar to Confidential Information.', 'hypothesis_id': 'nda-12', 'hypothesis_label': 'entailment', 'source_clause': "The obligations and restrictions imposed by this Agreement will not apply to any information that:. d. was independently developed by the Recipient without use of the Discloser's Confidential Information; or"}
 {'hypothesis': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.', 'hypothesis_id': 'nda-20', 'hypothesis_label': 'entailment', 'source_clause': 'e. Return of Information. on a Party\'s request, the other Party shall return all Confidential Information of the requesting Party, except for that portion of such Confidential Information that may be found in analyses prepared by, or for, the returning Party (collectively, "Analyses"), and the returning Party and its Representatives shall not retain any copies of such Confidential Information except the returning Party may retain one copy of the Confidential Information as needed to comply with applicable law and/or returning Party\'s record retention policies. '}
 {'hypothesis': 'Confidential Information may include verbally conveyed information.', 'hypothesis_id': 'nda-3', 'hypothesis_label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': "Receiving Party shall not solicit some of Disclosing Party's representatives.", 'hypothesis_id': 'nda-18', 'hypothesis_label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).', 'hypothesis_id': 'nda-7', 'hypothesis_label': 'entailment', 'source_clause': 'The Parties will:. a. limit disclosure of any Confidential Information to its directors, officers, employees, agents or representatives (collectively "Representatives") who have a need to know such Confidential Information in connection with the Transaction, and only for that purpose;'}
 {'hypothesis': 'Receiving Party may create a copy of some Confidential Information in some circumstances.', 'hypothesis_id': 'nda-17', 'hypothesis_label': 'entailment', 'source_clause': 'e. Return of Information. on a Party\'s request, the other Party shall return all Confidential Information of the requesting Party, except for that portion of such Confidential Information that may be found in analyses prepared by, or for, the returning Party (collectively, "Analyses"), and the returning Party and its Representatives shall not retain any copies of such Confidential Information except the returning Party may retain one copy of the Confidential Information as needed to comply with applicable law and/or returning Party\'s record retention policies. '}
 {'hypothesis': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.', 'hypothesis_id': 'nda-8', 'hypothesis_label': 'entailment', 'source_clause': 'a. The Recipient may disclose Confidential Information pursuant to any governmental, judicial, or administrative order, subpoena, discovery request, regulatory request or similar method, provided that the Recipient promptly notifies, to the extent practicable.'}
 {'hypothesis': 'Receiving Party may acquire information similar to Confidential Information from a third party.', 'hypothesis_id': 'nda-13', 'hypothesis_label': 'entailment', 'source_clause': "The obligations and restrictions imposed by this Agreement will not apply to any information that:. c. was received by the Recipient without breach of this Agreement from a third party without restriction as to the use and disclosure of the Discloser's Confidential Information; or,"}
 {'hypothesis': "Receiving Party may share some Confidential Information with some of Receiving Party's employees.", 'hypothesis_id': 'nda-5', 'hypothesis_label': 'entailment', 'source_clause': 'The Parties will:. a. limit disclosure of any Confidential Information to its directors, officers, employees, agents or representatives (collectively "Representatives") who have a need to know such Confidential Information in connection with the Transaction, and only for that purpose;. The Receiving Party agrees to use the same degree of protection it uses for its own trade secret information, and in no event less than reasonable efforts, to prevent and protect the Confidential Information, or any part thereof, from disclosure to any person other than the Receiving Party\'s employees having a need for disclosure in connection with the Receiving Party\'s authorized use of the Confidential Information.'}
 {'hypothesis': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.', 'hypothesis_id': 'nda-4', 'hypothesis_label': 'entailment', 'source_clause': 'The Parties agree to use the Confidential Information solely in connection with the Transaction and not for any purpose other than as authorized by this Agreement without the prior written consent of an authorized representative of the Parties. . The Parties agree to ensure that all copyright products, such as source codes, system design data/architecture, and other proprietary information, disclosed during the engagement is protected from any misuse, alteration, modification, sharing, or transfer to any party without express permission of the Discloser. . Such data is provided for the sole use of the Parties, and limited for the use under this agreement.. The Receiving Party agrees not to use the Confidential Information in any way, or to manufacture or test any product embodying Confidential Information, except for the purpose set forth above.'}]

In [ ]:
"""
# I blame mlrun for this weird behaviour, instead of the URI on the UI with the ://files path segment, it uses ://datasets
# Now that we are not using 
artifact_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_test_data:latest"

data_item = mlrun.get_dataitem(artifact_uri)
s3_path = data_item.url
print(s3_path) 

import pandas as pd
import io

raw_bytes = data_item.get()
df = pd.read_json(io.BytesIO(raw_bytes), orient="records", lines=True)

inferences = df.head(1)['inference'][0]
for i in inferences:
    print(i)
"""

s3://legal-llama-data/processed_training/20260412_1911/raw-proc-process-raw/0/test_data.jsonl

In [ ]:
asdasd

In [58]:
# This deletes all artifacts in the database
db = mlrun.get_run_db()
# Wipe all artifacts (including datasets) from this specific project
db.del_artifacts(project=project.metadata.name)

In [10]:
project.spec.get_code_path()

'../'